# Generated by Django 3.2.16 on 2023-06-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_useraccount_tipo_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='verified',
        ),
    ]
