# Generated by Django 3.2.16 on 2023-06-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230618_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('tecnico', 'Tecnico')], default='Tecnico', max_length=100),
        ),
    ]
