# Generated by Django 3.2.16 on 2023-06-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contratacion'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
