# Generated by Django 3.2.16 on 2023-06-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230620_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='fecha_contratacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Tecnico', 'Tecnico')], default='Tecnico', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
