# Generated by Django 3.2.16 on 2023-06-20 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230620_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contratacion'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('tecnico', 'Tecnico')], default='Tecnico', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
