# Generated by Django 3.2.16 on 2023-06-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20230528_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='numero_identificacion',
            new_name='dpi',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fecha_contratacion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='informacion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ubicacion',
        ),
    ]
