# Generated by Django 3.2.16 on 2023-06-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20230620_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dpi',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
